version: '3.8'
services:
 broker-db:
  container_name: mysqldb
  image: mysql:8.0.28
  restart: always
  ports:
    - 3306:3306
  environment:
    - MYSQL_DATABASE=stocks
    - MYSQL_ROOT_PASSWORD=priya1234

 broker-app:
  container_name: broker-container
  image: broker-image
  restart: on-failure
  ports:
    - 9090:8080
  environment:
    - DB_HOST=broker-db
    - DB_SCHEMA=stocks

